2015-09-16 13:16:17,401 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-4 - Starting application default Akka system: application
2015-09-16 13:16:17,468 [INFO] from play.core.server.NettyServer in pool-4-thread-4 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2015-09-16 13:16:39,076 [INFO] from play.api.libs.concurrent.ActorSystemProvider in ForkJoinPool-1-worker-1 - Starting application default Akka system: application
2015-09-16 13:16:40,739 [INFO] from play.api.Play in ForkJoinPool-1-worker-1 - Application started (Dev)
2015-09-16 13:17:20,369 [ERROR] from play.core.server.netty.PlayDefaultUpstreamHandler in application-akka.actor.default-dispatcher-13 - Cannot invoke the action
java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140) ~[async-http-client-1.9.21.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.3.Final.jar:na]
	... 8 common frames omitted
2015-09-16 13:17:20,424 [ERROR] from application in application-akka.actor.default-dispatcher-13 - 

! @6nf55allg - Internal server error, for (POST) [/signIn] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ConnectException: Connection refused: localhost/127.0.0.1:7474]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140) ~[async-http-client-1.9.21.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.3.Final.jar:na]
	... 8 common frames omitted
2015-09-16 13:17:20,729 [ERROR] from play.core.server.netty.PlayDefaultUpstreamHandler in application-akka.actor.default-dispatcher-10 - Cannot invoke the action
java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140) ~[async-http-client-1.9.21.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.3.Final.jar:na]
	... 8 common frames omitted
2015-09-16 13:17:20,731 [ERROR] from application in application-akka.actor.default-dispatcher-10 - 

! @6nf55am7d - Internal server error, for (POST) [/signIn] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ConnectException: Connection refused: localhost/127.0.0.1:7474]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140) ~[async-http-client-1.9.21.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:7474
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_60]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_60]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.3.Final.jar:na]
	... 8 common frames omitted
2015-09-16 13:19:30,566 [ERROR] from application in application-akka.actor.default-dispatcher-25 - 

! @6nf55i694 - Internal server error, for (GET) [/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[FileNotFoundException: /media/ajay/D/my_projects/play-silhouette-angular-seed-2/ui/app/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap (Is a directory)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.io.FileNotFoundException: /media/ajay/D/my_projects/play-silhouette-angular-seed-2/ui/app/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_60]
	at play.api.libs.iteratee.Enumerator$.fromFile(Enumerator.scala:584) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Results$Status.sendFile(Results.scala:416) ~[play_2.11-2.4.2.jar:2.4.2]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1$$anonfun$4.apply(Yeoman.scala:80) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1$$anonfun$4.apply(Yeoman.scala:79) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Filtered$$anonfun$foreach$4.apply(TraversableViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqLike$$anon$2.foreach(SeqLike.scala:671) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Filtered$class.foreach(TraversableViewLike.scala:196) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$5.foreach(SeqViewLike.scala:199) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Transformed$class.headOption(TraversableViewLike.scala:110) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$AbstractTransformed.headOption(SeqViewLike.scala:37) ~[scala-library-2.11.7.jar:na]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1.apply(Yeoman.scala:84) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1.apply(Yeoman.scala:69) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
	... 6 common frames omitted
2015-09-16 13:19:33,868 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-27 - AnyContentAsJson({"code":"AQAxCIdB0t8P4THVl4FNVmOrM5U7hd5D0AGEQIpWFP-oNHysxw2x5wZQfcnmUyRrpTVN1FXylmfDNIIkYLJpakS_nz9q9aIrscPv6hObugKt42629wRcTvbP8fIDlQzBwYMo8m134F68jt2CX_VvQzirOdSFIbcMIt7eESZa4PfqsLXDbUYYkcZnFdGRm6nka6N9yv8DlhKrFTpjsz5WleMZanel_A7gX_biy9mbCYHJTLGbDsUqepOxKIwcGzV7MJ_-qBSlMGnIzQjzX2eqxgw_RVNFjUvhDACCIx7cC1_fO_489KXn8KsHq6OgIcijR1A","clientId":"1503078423241610","redirectUri":"http://localhost:9000/"})
2015-09-16 13:19:33,875 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-27 - facebook
2015-09-16 13:19:34,542 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-27 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][facebook] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.util.Either.fold(Either.scala:98) ~[scala-library-2.11.7.jar:na]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:164) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.oauth2.FacebookProvider.buildInfo(FacebookProvider.scala:113) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:153) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:151) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
2015-09-16 13:23:44,969 [ERROR] from application in application-akka.actor.default-dispatcher-32 - 

! @6nf566ihn - Internal server error, for (GET) [/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[FileNotFoundException: /media/ajay/D/my_projects/play-silhouette-angular-seed-2/ui/app/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap (Is a directory)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.io.FileNotFoundException: /media/ajay/D/my_projects/play-silhouette-angular-seed-2/ui/app/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap (Is a directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_60]
	at play.api.libs.iteratee.Enumerator$.fromFile(Enumerator.scala:584) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Results$Status.sendFile(Results.scala:416) ~[play_2.11-2.4.2.jar:2.4.2]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1$$anonfun$4.apply(Yeoman.scala:80) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1$$anonfun$4.apply(Yeoman.scala:79) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Filtered$$anonfun$foreach$4.apply(TraversableViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqLike$$anon$2.foreach(SeqLike.scala:671) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Filtered$class.foreach(TraversableViewLike.scala:196) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$5.foreach(SeqViewLike.scala:199) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Transformed$class.headOption(TraversableViewLike.scala:110) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$AbstractTransformed.headOption(SeqViewLike.scala:37) ~[scala-library-2.11.7.jar:na]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1.apply(Yeoman.scala:84) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at com.tuplejump.playYeoman.DevAssets$$anonfun$assetHandler$1.apply(Yeoman.scala:69) ~[play-yeoman_2.11-0.8.1.jar:0.8.1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:439) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.7.jar:na]
	... 6 common frames omitted
2015-09-16 13:24:02,524 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - AnyContentAsJson({"code":"4/MHdjgD6lzAhBxQfs-XjA4otY7RvJO2zbjTM8N3WhrVg","clientId":"526391676642-nbnoavs078shhti3ruk8jhl4nenv0g04.apps.googleusercontent.com","redirectUri":"http://localhost:9000"})
2015-09-16 13:24:02,524 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - google
2015-09-16 13:24:02,950 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.util.Either.fold(Either.scala:98) ~[scala-library-2.11.7.jar:na]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:164) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:120) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:153) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:151) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
2015-09-16 13:24:11,093 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-37 - AnyContentAsJson({"code":"4/TcL98V4-_XGkdTIas0XQXkNqauz2THcJfOaZySM-Y7g","clientId":"526391676642-nbnoavs078shhti3ruk8jhl4nenv0g04.apps.googleusercontent.com","redirectUri":"http://localhost:9000"})
2015-09-16 13:24:11,093 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-37 - google
2015-09-16 13:24:11,179 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-38 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.util.Either.fold(Either.scala:98) ~[scala-library-2.11.7.jar:na]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:164) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.oauth2.GoogleProvider.buildInfo(GoogleProvider.scala:120) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:153) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:151) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
2015-09-16 13:24:31,214 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - AnyContentAsJson({"code":"AQDUhOSWamBlnf8RSWdtLBK7-ziJmF-BTjK0qCr4x9wELMZyAQyrMZ-nHEEO4RmAuJ4rAItQOZqvEdDHEzI85Iy_7irhs3SyTRs7KHpYBXEk9vn_Wx09D0UlOOLRCn6GrhhFpGIWoB8f2m5oqap_-lOoQW-CMdN_Y-F6pkaPZf7hs4BvUIMOJKk7RsnbceEJoJBoaNoJbmx5-_cI3eDh5DitsUw7vyxGFEF8vPgc82v8QC87B5grVOoWJ-7QcNe6sS9K-xAp4_zesxAqd5ogoNtVu2ppXgMuwFhm8NfQIQNQiwQW6rmz2KonBMxDeaX-5oM","clientId":"1503078423241610","redirectUri":"http://localhost:9000/"})
2015-09-16 13:24:31,214 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - facebook
2015-09-16 13:24:31,688 [ERROR] from controllers.SocialAuthController in application-akka.actor.default-dispatcher-22 - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][facebook] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.util.Either.fold(Either.scala:98) ~[scala-library-2.11.7.jar:na]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$class.buildInfo(OAuth2Provider.scala:164) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.oauth2.FacebookProvider.buildInfo(FacebookProvider.scala:113) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:153) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:151) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
2015-09-16 13:28:56,482 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-4 - Shutdown application default Akka system: application
